### ISSUE TITLE
Fix rubocop violations

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#183]
```
$ bundle exec rubocop

27 files inspected, 46 offenses detected
```

**Comment by jmccaffrey** [comment]
Here's an up-to-date look at what those rubocop violations are, via RefactorCop.
http://refactorcop.com/gmailgem/gmail
many of them center around method length and cyclomatic complexity, basically "these methods are complex and possibly hard to understand..and possibly hard to test"

**Comment by bootstraponline** [comment]
```
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
```
